name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    # 10:00 AM IST  = 04:30 UTC
    - cron: '30 4 * * *'
    # 10:00 PM IST  = 16:30 UTC
    - cron: '30 16 * * *'

jobs:
  test:
    timeout-minutes: 70
    runs-on: ubuntu-latest

    env:
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      # Define the recipient groups using secrets
      FAILURE_ALERT_EMAILS: ${{ secrets.FAILURE_ALERT_EMAILS }}
      DAILY_REPORT_EMAILS: ${{ secrets.DAILY_REPORT_EMAILS }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test tests

      - name: Upload playwright-report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
